/**
 * Runtime GLSL material helpers — the shared toolbox for every system that
 * renders a surface. **Import read-only; do not edit this file from another
 * module.** Everything is prefixed `mx_` so it cannot collide with three's
 * shader chunks or with `NOISE_GLSL` / `COMMON_GLSL` from `core/Noise.ts`.
 *
 * Usage from `onBeforeCompile`:
 *
 * ```ts
 * import { MATERIAL_GLSL } from '../../assets/MaterialGlsl';
 *
 * mat.onBeforeCompile = (shader) => {
 *   shader.fragmentShader = shader.fragmentShader
 *     .replace('#include <common>', `#include <common>\n${MATERIAL_GLSL}`)
 *     .replace('#include <normal_fragment_maps>', MY_CUSTOM_NORMAL_CHUNK);
 * };
 * ```
 *
 * ### Map layout produced by `TextureLibrary.get()`
 * ```
 * map          rgb albedo (sRGB-decoded by hardware), a opacity/coverage
 * normalMap    rgb tangent-space normal, a HEIGHT  <-- parallax reads .a
 * roughnessMap == aoMap == the packed ORM texture:
 *              r ambient occlusion   (three's aoMap reads .r)
 *              g roughness           (three's roughnessMap reads .g)
 *              b metalness           (three's metalnessMap reads .b)
 *              a aux (emissive mask / iridescence mask / translucency)
 * displacementMap (some materials only)
 *              r height, g curvature (0.5-centred), b flow, a sparkle
 * ```
 * Height living in `normalMap.a` is deliberate: parallax occlusion mapping then
 * needs no extra texture fetch beyond the normal you were already sampling.
 *
 * ### What is in here
 * - `mx_blendNormalRNM`  reoriented normal mapping for detail layers
 * - `mx_hexSample`       stochastic hex-grid sampling to kill visible tiling
 * - `mx_triplanar*`      triplanar projection with correct normal reorientation
 * - `mx_parallax*`       parallax occlusion mapping + self-shadow
 * - `mx_curvature`       curvature from the packed height, for wear masks
 * - `mx_thinFilmIridescence`, `mx_macroVariation`, `mx_hueShift`
 */
export const MATERIAL_GLSL = /* glsl */ `
#ifndef MX_MATERIAL_GLSL
#define MX_MATERIAL_GLSL

const float MX_TAU = 6.28318530718;

/* ================================================================ *
 * Packing helpers
 * ================================================================ */

vec3 mx_unpackNormal(vec3 c){ return c * 2.0 - 1.0; }
vec3 mx_packNormal(vec3 n){ return n * 0.5 + 0.5; }

/** Height stored in the alpha of the normal map. */
float mx_height(sampler2D normalMap, vec2 uv){ return texture2D(normalMap, uv).a; }

float mx_luma(vec3 c){ return dot(c, vec3(0.2126, 0.7152, 0.0722)); }

vec3 mx_hueShift(vec3 c, float a){
  const vec3 k = vec3(0.57735);
  float ca = cos(a);
  return c * ca + cross(k, c) * sin(a) + k * dot(k, c) * (1.0 - ca);
}

vec3 mx_saturate(vec3 c, float s){ return mix(vec3(mx_luma(c)), c, s); }

/* ================================================================ *
 * Detail-normal blending
 * ================================================================ */

/**
 * Reoriented Normal Mapping (Barre-Brisebois & Hill, 2012). Rotates the detail
 * normal into the base normal's frame. This is the correct way to layer normal
 * maps; naive addition flattens the base and naive whiteout over-sharpens.
 * Both inputs must be unpacked, unit-length tangent-space normals.
 */
vec3 mx_blendNormalRNM(vec3 base, vec3 detail){
  vec3 t = base + vec3(0.0, 0.0, 1.0);
  vec3 u = detail * vec3(-1.0, -1.0, 1.0);
  return normalize(t * dot(t, u) - u * t.z);
}

/** Whiteout blend — cheaper, slightly stronger. Fine for grunge overlays. */
vec3 mx_blendNormalWhiteout(vec3 base, vec3 detail){
  return normalize(vec3(base.xy + detail.xy, base.z * detail.z));
}

/** Scale a tangent-space normal's slope without denormalising it. */
vec3 mx_scaleNormal(vec3 n, float s){ return normalize(vec3(n.xy * s, n.z)); }

/* ================================================================ *
 * Anti-tiling
 * ================================================================ */

vec2 mx_hash22(vec2 p){
  vec3 p3 = fract(vec3(p.xyx) * vec3(0.1031, 0.1030, 0.0973));
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.xx + p3.yz) * p3.zy);
}

/**
 * Triangle/hex grid used by stochastic hex tiling (Heitz & Neyret 2018, and the
 * real-time formulation by Mikkelsen). Splits uv space into equilateral
 * triangles and returns the three surrounding lattice vertices plus barycentric
 * weights, so three randomly offset copies of a texture can be blended with no
 * visible grid.
 */
void mx_triangleGrid(vec2 uv, out vec3 w, out vec2 v1, out vec2 v2, out vec2 v3){
  uv *= 3.4641016;                              // 2*sqrt(3)
  const mat2 toSkewed = mat2(1.0, 0.0, -0.5773503, 1.1547005);
  vec2 skewed = toSkewed * uv;
  vec2 base = floor(skewed);
  vec3 t = vec3(fract(skewed), 0.0);
  t.z = 1.0 - t.x - t.y;
  if (t.z > 0.0){
    w = vec3(t.z, t.y, t.x);
    v1 = base;
    v2 = base + vec2(0.0, 1.0);
    v3 = base + vec2(1.0, 0.0);
  } else {
    w = vec3(-t.z, 1.0 - t.y, 1.0 - t.x);
    v1 = base + vec2(1.0, 1.0);
    v2 = base + vec2(1.0, 0.0);
    v3 = base + vec2(0.0, 1.0);
  }
}

/**
 * Stochastic hex-grid sample: three taps of the same texture at randomised
 * offsets, blended by sharpened barycentric weights. Removes the repeating grid
 * that any tiled texture shows past ~10 m. 'contrast' in [1, 8]; higher keeps
 * more of a single tap and preserves detail contrast but shows the blend more.
 */
vec4 mx_hexSample(sampler2D tex, vec2 uv, float contrast){
  vec3 w; vec2 v1, v2, v3;
  mx_triangleGrid(uv, w, v1, v2, v3);
  vec4 c1 = texture2D(tex, uv + mx_hash22(v1));
  vec4 c2 = texture2D(tex, uv + mx_hash22(v2));
  vec4 c3 = texture2D(tex, uv + mx_hash22(v3));
  w = pow(w, vec3(contrast));
  w /= max(w.x + w.y + w.z, 1e-5);
  return c1 * w.x + c2 * w.y + c3 * w.z;
}

/** Hex-grid sample of a packed normal+height map, blended as vectors. */
vec4 mx_hexSampleNormal(sampler2D nmap, vec2 uv, float contrast){
  vec3 w; vec2 v1, v2, v3;
  mx_triangleGrid(uv, w, v1, v2, v3);
  vec4 s1 = texture2D(nmap, uv + mx_hash22(v1));
  vec4 s2 = texture2D(nmap, uv + mx_hash22(v2));
  vec4 s3 = texture2D(nmap, uv + mx_hash22(v3));
  w = pow(w, vec3(contrast));
  w /= max(w.x + w.y + w.z, 1e-5);
  vec3 n = normalize(mx_unpackNormal(s1.xyz) * w.x
                   + mx_unpackNormal(s2.xyz) * w.y
                   + mx_unpackNormal(s3.xyz) * w.z);
  float h = s1.a * w.x + s2.a * w.y + s3.a * w.z;
  return vec4(mx_packNormal(n), h);
}

/**
 * Two-tap stochastic variant: cheaper than hex, blends two randomly rotated and
 * offset copies keyed off a coarse cell. Good for distant LODs.
 */
vec4 mx_stochasticSample(sampler2D tex, vec2 uv, float cellScale){
  vec2 cell = floor(uv * cellScale);
  vec2 f = fract(uv * cellScale);
  vec2 oA = mx_hash22(cell);
  vec2 oB = mx_hash22(cell + 37.0);
  float t = smoothstep(0.35, 0.65, max(f.x, f.y));
  return mix(texture2D(tex, uv + oA), texture2D(tex, uv + oB), t);
}

/**
 * Low-frequency macro-variation multiply layer. The single cheapest fix for
 * "this 512px tile is obviously repeating": modulate value and hue on a scale
 * far larger than the tile.
 */
vec3 mx_macroVariation(vec3 albedo, sampler2D noiseTex, vec2 worldUv, float scale, float strength){
  vec3 n = texture2D(noiseTex, worldUv * scale).rgb;
  float v = n.r * 2.0 - 1.0;
  albedo *= 1.0 + v * strength;
  return mx_hueShift(albedo, (n.g - 0.5) * strength * 0.6);
}

/* ================================================================ *
 * Triplanar projection
 * ================================================================ */

vec3 mx_triWeights(vec3 n, float sharpness){
  vec3 w = pow(abs(n), vec3(sharpness));
  return w / max(w.x + w.y + w.z, 1e-5);
}

/** Triplanar colour sample. Axis flips keep the projections right-handed. */
vec4 mx_triplanar(sampler2D tex, vec3 wpos, vec3 wnrm, float scale, float sharpness){
  vec3 w = mx_triWeights(wnrm, sharpness);
  vec2 uvX = wpos.zy * scale; if (wnrm.x < 0.0) uvX.x = -uvX.x;
  vec2 uvY = wpos.xz * scale; if (wnrm.y < 0.0) uvY.x = -uvY.x;
  vec2 uvZ = wpos.xy * scale; if (wnrm.z > 0.0) uvZ.x = -uvZ.x;
  return texture2D(tex, uvX) * w.x + texture2D(tex, uvY) * w.y + texture2D(tex, uvZ) * w.z;
}

/**
 * Triplanar normal with correct per-axis reorientation (whiteout formulation).
 * Returns a WORLD-space normal. The common mistake is blending the three
 * tangent-space samples directly, which leaves the detail pointing the wrong way
 * on two of the three planes.
 */
vec3 mx_triplanarNormal(sampler2D nmap, vec3 wpos, vec3 wnrm, float scale, float sharpness){
  vec3 w = mx_triWeights(wnrm, sharpness);
  vec2 uvX = wpos.zy * scale; if (wnrm.x < 0.0) uvX.x = -uvX.x;
  vec2 uvY = wpos.xz * scale; if (wnrm.y < 0.0) uvY.x = -uvY.x;
  vec2 uvZ = wpos.xy * scale; if (wnrm.z > 0.0) uvZ.x = -uvZ.x;

  vec3 tx = mx_unpackNormal(texture2D(nmap, uvX).xyz);
  vec3 ty = mx_unpackNormal(texture2D(nmap, uvY).xyz);
  vec3 tz = mx_unpackNormal(texture2D(nmap, uvZ).xyz);

  vec3 nx = vec3(tx.xy + wnrm.zy, abs(tx.z) * wnrm.x);
  vec3 ny = vec3(ty.xy + wnrm.xz, abs(ty.z) * wnrm.y);
  vec3 nz = vec3(tz.xy + wnrm.xy, abs(tz.z) * wnrm.z);

  return normalize(nx.zyx * w.x + ny.xzy * w.y + nz.xyz * w.z);
}

/** Triplanar height, for blending or for POM on a triplanar surface. */
float mx_triplanarHeight(sampler2D nmap, vec3 wpos, vec3 wnrm, float scale, float sharpness){
  vec3 w = mx_triWeights(wnrm, sharpness);
  return texture2D(nmap, wpos.zy * scale).a * w.x
       + texture2D(nmap, wpos.xz * scale).a * w.y
       + texture2D(nmap, wpos.xy * scale).a * w.z;
}

/* ================================================================ *
 * Parallax occlusion mapping
 * ================================================================ */

/**
 * Steep parallax march with a secant refinement, reading height from
 * 'normalMap.a'. 'viewTS' is the *tangent-space* view direction pointing from
 * the surface toward the eye; 'depth' is the relief height in uv units
 * (0.02-0.06 is a sane range). Returns the parallax-corrected uv.
 *
 * Fade 'depth' toward 0 with distance or the silhouette will swim.
 */
vec2 mx_parallaxOcclusion(sampler2D nmap, vec2 uv, vec3 viewTS, float depth, int steps){
  if (viewTS.z <= 0.001 || depth <= 0.0) return uv;
  float layer = 1.0 / float(steps);
  vec2 delta = (viewTS.xy / max(viewTS.z, 0.20)) * depth * layer;
  float cur = 0.0;
  vec2 p = uv;
  float h = 1.0 - texture2D(nmap, p).a;
  for (int i = 0; i < 32; i++){
    if (i >= steps || cur >= h) break;
    p -= delta;
    h = 1.0 - texture2D(nmap, p).a;
    cur += layer;
  }
  vec2 prev = p + delta;
  float after = h - cur;
  float before = (1.0 - texture2D(nmap, prev).a) - (cur - layer);
  return mix(p, prev, clamp(after / max(after - before, 1e-4), 0.0, 1.0));
}

/**
 * Parallax self-shadowing: marches toward the light and returns a soft
 * visibility term in [0, 1]. Cheap way to make relief read as geometry rather
 * than as a normal map.
 */
float mx_parallaxShadow(sampler2D nmap, vec2 uv, vec3 lightTS, float depth, int steps){
  if (lightTS.z <= 0.001 || depth <= 0.0) return 1.0;
  float h0 = texture2D(nmap, uv).a;
  vec2 delta = (lightTS.xy / max(lightTS.z, 0.20)) * depth / float(steps);
  float occ = 0.0;
  for (int i = 1; i <= 16; i++){
    if (i > steps) break;
    float t = float(i) / float(steps);
    float hs = texture2D(nmap, uv + delta * float(i)).a;
    occ = max(occ, (hs - (h0 + t * depth * 2.0)) * (1.0 - t));
  }
  return clamp(1.0 - occ * 6.0, 0.0, 1.0);
}

/* ================================================================ *
 * Curvature / wear masks
 * ================================================================ */

/**
 * Curvature of the packed height field: > 0 in cavities, < 0 on convex edges.
 * Drives grime accumulation and edge wear from the same source of truth the
 * normal map came from. 'texel' is 1/textureSize; 'radius' in texels.
 */
float mx_curvature(sampler2D nmap, vec2 uv, vec2 texel, float radius){
  float c = texture2D(nmap, uv).a;
  float l = texture2D(nmap, uv - vec2(texel.x * radius, 0.0)).a;
  float r = texture2D(nmap, uv + vec2(texel.x * radius, 0.0)).a;
  float d = texture2D(nmap, uv - vec2(0.0, texel.y * radius)).a;
  float u = texture2D(nmap, uv + vec2(0.0, texel.y * radius)).a;
  return ((l + r + d + u) * 0.25 - c) * 4.0;
}

float mx_cavityMask(float curvature, float gain){ return clamp(curvature * gain, 0.0, 1.0); }
float mx_wearMask(float curvature, float gain){ return clamp(-curvature * gain, 0.0, 1.0); }

/* ================================================================ *
 * Height blending (for terrain/material transitions)
 * ================================================================ */

/**
 * Height-aware two-layer blend weight. Keeps whichever layer has more relief on
 * top instead of cross-dissolving both into mush.
 */
float mx_heightBlend(float hA, float hB, float t, float sharpness){
  float a = hA * (1.0 - t);
  float b = hB * t;
  float m = max(a, b) - sharpness;
  float wa = max(a - m, 0.0);
  float wb = max(b - m, 0.0);
  return wb / max(wa + wb, 1e-5);
}

/* ================================================================ *
 * Iridescence
 * ================================================================ */

/**
 * Cheap thin-film interference tint. Baked maps carry only the iridescence
 * *mask* (ORM alpha on the skin materials) because the effect is view
 * dependent; multiply this by that mask in the creature shader.
 * 'thickness' in [0, 1] shifts the fringe order.
 */
vec3 mx_thinFilmIridescence(float NdotV, float thickness, float strength){
  float t = (1.0 - clamp(NdotV, 0.0, 1.0)) * 3.0 + thickness * 4.0;
  vec3 phase = vec3(t, t * 1.16, t * 1.34) * MX_TAU;
  vec3 tint = 0.5 + 0.5 * cos(phase);
  return mix(vec3(1.0), tint * 1.35, strength);
}

/* ================================================================ *
 * Misc
 * ================================================================ */

/** Interleaved-gradient noise — pairs well with the blue-noise texture. */
float mx_ign(vec2 pixel){
  return fract(52.9829189 * fract(dot(pixel, vec2(0.06711056, 0.00583715))));
}

/** Dither a value with the blue-noise tile to kill banding before quantisation. */
vec3 mx_dither(vec3 c, sampler2D blueNoise, vec2 pixel, float amount){
  float n = texture2D(blueNoise, pixel / 128.0).r - 0.5;
  return c + n * amount;
}

#endif
`;

/** Convenience: the map layout, as a comment block to paste into a shader. */
export const MATERIAL_MAP_LAYOUT = `map.rgb=albedo map.a=opacity | normalMap.rgb=normal normalMap.a=height | orm(=roughnessMap=aoMap): r=ao g=roughness b=metalness a=aux`;
