/**
 * The species roster. Ids match the `flora` entries in
 * `world/terrain/Biomes.ts`, which is what drives population density per biome.
 */
import * as THREE from 'three';
import type { FloraFamily } from './FloraTextures';
import type { ShapeBuilder } from './FloraShapes';
import {
  buildAlgaeMat,
  buildBarrelSponge,
  buildBioStalk,
  buildBloodKelp,
  buildBrainCoral,
  buildFanCoral,
  buildGiantKelp,
  buildLavaCoral,
  buildSeagrass,
  buildShortKelp,
  buildTreeMushroom,
  buildTubeCoral,
} from './FloraShapes';

const lin = (hex: number) => new THREE.Color(hex).convertSRGBToLinear();

export interface SpeciesDef {
  id: string;
  family: FloraFamily;
  build: ShapeBuilder;

  /* --- appearance --- */
  color: THREE.Color;
  /** Per-instance HSL jitter ranges applied to a white multiplier. */
  tintHue: number;
  tintSat: number;
  tintLum: number;
  roughness: number;
  metalness: number;
  normalScale: number;
  texScale: number;
  microScale: number;
  microAmt: number;
  macroScale: number;
  macroAmt: number;
  aoAmt: number;

  /* --- translucency / sheen / emission --- */
  transColor: THREE.Color;
  transStrength: number;
  transPower: number;
  sheen: number;
  sheenGloss: number;
  emissiveColor: THREE.Color;
  emissiveStrength: number;
  emissivePulse: number;

  /* --- animation --- */
  swayAmp: number;
  swayFreq: number;
  stiffness: number;
  undulate: number;
  waveScale: number;
  flutter: number;

  /* --- placement --- */
  minDepth: number;
  maxDepth: number;
  /** Reject candidates whose terrain normal.y falls below this (slope gate). */
  minNormalY: number;
  /** Relative abundance on top of the biome's own density. */
  densityMul: number;
  /** Minimum separation in metres (Poisson-ish rejection). */
  spacing: number;
  /** Patchiness: noise frequency and strength, so beds form instead of a wash. */
  clumpFreq: number;
  clumpAmt: number;
  scaleMin: number;
  scaleMax: number;
  /** 0 = always upright, 1 = fully aligned with the sea-floor normal. */
  alignToNormal: number;
  /** Metres of the base to bury so nothing floats above the sand. */
  sink: number;
  /** Per-instance twist / lean warp magnitudes. */
  twistAmt: number;
  leanAmt: number;

  /* --- LOD --- */
  /** Boundaries in metres: [mesh->simple, simple->card, cull]. */
  lodDist: [number, number, number];
  variants: [number, number];
  alphaMode: 'blade' | 'card' | 'none';
  alphaTest: number;
  cardQuads: number;
  cardHorizontal: boolean;
}

type Partialish = Partial<SpeciesDef> & Pick<SpeciesDef, 'id' | 'family' | 'build' | 'color'>;

const DEFAULTS: Omit<SpeciesDef, 'id' | 'family' | 'build' | 'color'> = {
  tintHue: 0.045,
  tintSat: 0.14,
  tintLum: 0.14,
  roughness: 0.62,
  metalness: 0,
  normalScale: 1.0,
  texScale: 1,
  microScale: 9,
  microAmt: 0.32,
  macroScale: 0.021,
  macroAmt: 0.30,
  aoAmt: 0.85,
  transColor: lin(0xbfe08a),
  transStrength: 1.6,
  transPower: 3.0,
  sheen: 0.25,
  sheenGloss: 26,
  emissiveColor: lin(0x33e6ff),
  emissiveStrength: 0,
  emissivePulse: 1.1,
  swayAmp: 0.5,
  swayFreq: 0.55,
  stiffness: 1.6,
  undulate: 0.5,
  waveScale: 5.0,
  flutter: 0.03,
  minDepth: 0,
  maxDepth: 1400,
  minNormalY: 0.62,
  densityMul: 1,
  spacing: 1.2,
  clumpFreq: 0.022,
  clumpAmt: 1.0,
  scaleMin: 0.8,
  scaleMax: 1.25,
  alignToNormal: 0.35,
  sink: 0.06,
  twistAmt: 0.4,
  leanAmt: 0.12,
  lodDist: [32, 70, 130],
  variants: [3, 2],
  alphaMode: 'blade',
  alphaTest: 0.42,
  cardQuads: 2,
  cardHorizontal: false,
};

function def(p: Partialish): SpeciesDef {
  return { ...DEFAULTS, ...p } as SpeciesDef;
}

export const SPECIES: SpeciesDef[] = [
  /* ---------------------------------------------------------------- *
   * Kelps
   * ---------------------------------------------------------------- */
  def({
    id: 'kelp_giant',
    family: 'blade',
    build: buildGiantKelp,
    color: lin(0x7d8438),
    tintHue: 0.055,
    tintLum: 0.18,
    roughness: 0.52,
    texScale: 1,
    microScale: 11,
    microAmt: 0.34,
    macroScale: 0.013,
    macroAmt: 0.34,
    transColor: lin(0xd6e88c),
    transStrength: 2.35,
    transPower: 2.4,
    sheen: 0.42,
    sheenGloss: 34,
    swayAmp: 1.35,
    swayFreq: 0.42,
    stiffness: 1.45,
    undulate: 0.85,
    waveScale: 7.5,
    flutter: 0.075,
    minDepth: 12,
    maxDepth: 135,
    minNormalY: 0.66,
    densityMul: 1.0,
    spacing: 2.1,
    clumpFreq: 0.014,
    clumpAmt: 1.35,
    scaleMin: 0.72,
    scaleMax: 1.30,
    alignToNormal: 0.14,
    sink: 0.25,
    twistAmt: 0.7,
    leanAmt: 0.7,
    lodDist: [58, 132, 235],
    variants: [4, 2],
    cardQuads: 3,
  }),
  def({
    id: 'kelp_short',
    family: 'blade',
    build: buildShortKelp,
    color: lin(0x86993c),
    tintHue: 0.06,
    roughness: 0.5,
    microScale: 8,
    transColor: lin(0xd2e58a),
    transStrength: 2.2,
    transPower: 2.6,
    sheen: 0.38,
    swayAmp: 0.52,
    swayFreq: 0.62,
    stiffness: 1.35,
    undulate: 0.60,
    waveScale: 4.5,
    flutter: 0.055,
    minDepth: 2,
    maxDepth: 90,
    densityMul: 1.15,
    spacing: 0.95,
    clumpFreq: 0.02,
    clumpAmt: 1.2,
    scaleMin: 0.65,
    scaleMax: 1.4,
    alignToNormal: 0.3,
    sink: 0.1,
    twistAmt: 0.9,
    leanAmt: 0.35,
    lodDist: [32, 72, 132],
  }),
  def({
    id: 'blood_kelp',
    family: 'blade',
    build: buildBloodKelp,
    color: lin(0x74222a),
    tintHue: 0.03,
    tintLum: 0.2,
    roughness: 0.46,
    microScale: 10,
    macroScale: 0.015,
    transColor: lin(0xff6a58),
    transStrength: 2.0,
    transPower: 2.2,
    sheen: 0.34,
    emissiveColor: lin(0xff5a4a),
    emissiveStrength: 1.5,
    emissivePulse: 0.7,
    swayAmp: 1.0,
    swayFreq: 0.30,
    stiffness: 1.55,
    undulate: 0.80,
    waveScale: 6.5,
    flutter: 0.05,
    minDepth: 180,
    maxDepth: 560,
    densityMul: 1.0,
    spacing: 2.4,
    clumpFreq: 0.012,
    clumpAmt: 1.3,
    scaleMin: 0.7,
    scaleMax: 1.35,
    alignToNormal: 0.16,
    sink: 0.3,
    twistAmt: 0.6,
    leanAmt: 0.6,
    lodDist: [52, 120, 220],
    cardQuads: 3,
  }),

  /* ---------------------------------------------------------------- *
   * Grasses and mats
   * ---------------------------------------------------------------- */
  def({
    id: 'seagrass',
    family: 'blade',
    build: buildSeagrass,
    color: lin(0x74a044),
    tintHue: 0.07,
    tintSat: 0.18,
    tintLum: 0.2,
    roughness: 0.48,
    texScale: 1,
    microScale: 6,
    microAmt: 0.28,
    macroScale: 0.03,
    macroAmt: 0.36,
    transColor: lin(0xd8f096),
    transStrength: 2.5,
    transPower: 2.0,
    sheen: 0.3,
    swayAmp: 0.22,
    swayFreq: 0.85,
    stiffness: 1.25,
    undulate: 0.45,
    waveScale: 3.2,
    flutter: 0.035,
    minDepth: 1,
    maxDepth: 180,
    minNormalY: 0.70,
    densityMul: 1.7,
    spacing: 0.42,
    clumpFreq: 0.035,
    clumpAmt: 1.25,
    scaleMin: 0.6,
    scaleMax: 1.5,
    alignToNormal: 0.55,
    sink: 0.05,
    twistAmt: 1.1,
    leanAmt: 0.2,
    lodDist: [24, 50, 92],
    variants: [3, 2],
    cardHorizontal: true,
  }),
  def({
    id: 'algae_mat',
    family: 'blade',
    build: buildAlgaeMat,
    color: lin(0x4e7a4c),
    tintHue: 0.05,
    roughness: 0.55,
    microScale: 7,
    macroScale: 0.028,
    transColor: lin(0xa8d878),
    transStrength: 1.9,
    sheen: 0.28,
    swayAmp: 0.14,
    swayFreq: 0.7,
    stiffness: 1.1,
    undulate: 0.35,
    waveScale: 2.6,
    flutter: 0.04,
    minDepth: 1,
    maxDepth: 200,
    minNormalY: 0.74,
    densityMul: 1.25,
    spacing: 0.7,
    clumpFreq: 0.03,
    clumpAmt: 1.2,
    scaleMin: 0.65,
    scaleMax: 1.45,
    alignToNormal: 0.85,
    sink: 0.03,
    twistAmt: 1.3,
    leanAmt: 0.15,
    lodDist: [22, 46, 86],
    cardHorizontal: true,
  }),

  /* ---------------------------------------------------------------- *
   * Corals and sponges
   * ---------------------------------------------------------------- */
  def({
    id: 'coral_brain',
    family: 'crust',
    build: buildBrainCoral,
    color: lin(0xc4855c),
    tintHue: 0.05,
    tintSat: 0.2,
    tintLum: 0.16,
    roughness: 0.82,
    normalScale: 1.35,
    texScale: 1,
    microScale: 6,
    microAmt: 0.34,
    macroScale: 0.024,
    macroAmt: 0.28,
    aoAmt: 0.95,
    transColor: lin(0xffb489),
    transStrength: 0.45,
    transPower: 6.0,
    sheen: 0.1,
    sheenGloss: 14,
    swayAmp: 0.012,
    swayFreq: 0.5,
    stiffness: 3.0,
    undulate: 0.06,
    waveScale: 1.5,
    flutter: 0,
    minDepth: 6,
    maxDepth: 320,
    minNormalY: 0.52,
    densityMul: 0.9,
    spacing: 2.2,
    clumpFreq: 0.026,
    clumpAmt: 1.15,
    // Brain-coral boulders are 2-4 m across in Subnautica's reefs; at the old
    // 1.5x cap they topped out under 2 m and read as pebbles from 20 m up.
    scaleMin: 0.85,
    scaleMax: 2.5,
    alignToNormal: 0.75,
    sink: 0.14,
    twistAmt: 0.35,
    leanAmt: 0.05,
    lodDist: [46, 96, 172],
    alphaMode: 'none',
  }),
  def({
    id: 'coral_tube',
    family: 'crust',
    build: buildTubeCoral,
    color: lin(0xd07866),
    tintHue: 0.07,
    tintSat: 0.24,
    tintLum: 0.18,
    roughness: 0.72,
    normalScale: 1.2,
    microScale: 8,
    macroScale: 0.03,
    aoAmt: 0.95,
    transColor: lin(0xffa585),
    transStrength: 0.85,
    transPower: 4.0,
    sheen: 0.16,
    sheenGloss: 18,
    swayAmp: 0.02,
    swayFreq: 0.6,
    stiffness: 2.6,
    undulate: 0.1,
    waveScale: 2.0,
    flutter: 0,
    minDepth: 4,
    maxDepth: 260,
    minNormalY: 0.55,
    densityMul: 0.95,
    spacing: 1.7,
    clumpFreq: 0.03,
    clumpAmt: 1.2,
    scaleMin: 1.2,
    scaleMax: 3.0,
    alignToNormal: 0.7,
    sink: 0.08,
    twistAmt: 0.5,
    leanAmt: 0.08,
    lodDist: [40, 84, 152],
    alphaMode: 'none',
  }),
  def({
    id: 'coral_fan',
    family: 'crust',
    build: buildFanCoral,
    color: lin(0xc25a76),
    tintHue: 0.09,
    tintSat: 0.26,
    tintLum: 0.18,
    roughness: 0.68,
    normalScale: 1.1,
    microScale: 10,
    macroScale: 0.026,
    transColor: lin(0xff9ec0),
    transStrength: 1.15,
    transPower: 3.4,
    sheen: 0.2,
    sheenGloss: 20,
    swayAmp: 0.07,
    swayFreq: 0.75,
    stiffness: 2.1,
    undulate: 0.22,
    waveScale: 3.0,
    flutter: 0.008,
    minDepth: 3,
    maxDepth: 280,
    minNormalY: 0.48,
    densityMul: 0.85,
    spacing: 1.9,
    clumpFreq: 0.028,
    clumpAmt: 1.15,
    scaleMin: 0.9,
    scaleMax: 2.3,
    alignToNormal: 0.5,
    sink: 0.06,
    twistAmt: 0.6,
    leanAmt: 0.14,
    lodDist: [42, 88, 158],
    alphaMode: 'none',
  }),
  def({
    id: 'sponge',
    family: 'crust',
    build: buildBarrelSponge,
    color: lin(0xa8946a),
    tintHue: 0.06,
    tintSat: 0.2,
    tintLum: 0.18,
    roughness: 0.86,
    normalScale: 1.5,
    microScale: 7,
    microAmt: 0.36,
    macroScale: 0.022,
    aoAmt: 1.0,
    transColor: lin(0xffd8a0),
    transStrength: 0.5,
    transPower: 5.0,
    sheen: 0.08,
    sheenGloss: 12,
    swayAmp: 0.01,
    swayFreq: 0.4,
    stiffness: 3.2,
    undulate: 0.05,
    waveScale: 1.2,
    flutter: 0,
    minDepth: 20,
    maxDepth: 420,
    minNormalY: 0.60,
    densityMul: 0.7,
    spacing: 2.3,
    clumpFreq: 0.022,
    clumpAmt: 1.1,
    scaleMin: 0.75,
    scaleMax: 2.0,
    alignToNormal: 0.6,
    sink: 0.12,
    twistAmt: 0.3,
    leanAmt: 0.05,
    lodDist: [48, 100, 178],
    alphaMode: 'none',
  }),

  /* ---------------------------------------------------------------- *
   * Mushroom forest / bioluminescent / lava
   * ---------------------------------------------------------------- */
  def({
    id: 'tree_mushroom',
    family: 'flesh',
    build: buildTreeMushroom,
    color: lin(0x9d86b4),
    tintHue: 0.08,
    tintSat: 0.22,
    tintLum: 0.2,
    roughness: 0.55,
    normalScale: 0.9,
    microScale: 8,
    microAmt: 0.28,
    macroScale: 0.018,
    macroAmt: 0.32,
    transColor: lin(0xe8c8ff),
    transStrength: 1.5,
    transPower: 3.2,
    sheen: 0.3,
    sheenGloss: 22,
    swayAmp: 0.16,
    swayFreq: 0.35,
    stiffness: 2.3,
    undulate: 0.28,
    waveScale: 2.4,
    flutter: 0.006,
    minDepth: 70,
    maxDepth: 320,
    minNormalY: 0.66,
    densityMul: 0.85,
    spacing: 3.4,
    clumpFreq: 0.018,
    clumpAmt: 1.25,
    // Mushroom Forest trees are canopy-scale landmarks, 8-14 m tall.
    scaleMin: 0.9,
    scaleMax: 2.7,
    alignToNormal: 0.25,
    sink: 0.12,
    twistAmt: 0.5,
    leanAmt: 0.3,
    lodDist: [64, 136, 240],
    alphaMode: 'none',
    cardQuads: 3,
  }),
  def({
    id: 'bioluminescent',
    family: 'flesh',
    build: buildBioStalk,
    color: lin(0x3d5566),
    tintHue: 0.06,
    tintSat: 0.2,
    tintLum: 0.22,
    roughness: 0.42,
    normalScale: 0.8,
    microScale: 9,
    macroScale: 0.026,
    transColor: lin(0x9ce8ff),
    transStrength: 1.2,
    transPower: 3.0,
    sheen: 0.34,
    sheenGloss: 30,
    emissiveColor: lin(0x46e8ff),
    emissiveStrength: 2.3,
    emissivePulse: 1.4,
    swayAmp: 0.3,
    swayFreq: 0.5,
    stiffness: 1.4,
    undulate: 0.7,
    waveScale: 5.0,
    flutter: 0.02,
    minDepth: 60,
    maxDepth: 900,
    minNormalY: 0.6,
    densityMul: 1.1,
    spacing: 0.9,
    clumpFreq: 0.028,
    clumpAmt: 1.3,
    scaleMin: 0.6,
    scaleMax: 1.55,
    alignToNormal: 0.4,
    sink: 0.06,
    twistAmt: 0.9,
    leanAmt: 0.3,
    lodDist: [42, 90, 168],
    alphaMode: 'none',
  }),
  def({
    id: 'lava_coral',
    family: 'crust',
    build: buildLavaCoral,
    color: lin(0x33231e),
    tintHue: 0.04,
    tintSat: 0.16,
    tintLum: 0.22,
    roughness: 0.9,
    normalScale: 1.6,
    microScale: 7,
    microAmt: 0.38,
    macroScale: 0.024,
    aoAmt: 1.0,
    transColor: lin(0xff8a3a),
    transStrength: 0.35,
    transPower: 6.0,
    sheen: 0.06,
    sheenGloss: 10,
    emissiveColor: lin(0xff5a18),
    emissiveStrength: 2.6,
    emissivePulse: 0.5,
    swayAmp: 0.008,
    swayFreq: 0.3,
    stiffness: 3.2,
    undulate: 0.04,
    waveScale: 1.2,
    flutter: 0,
    minDepth: 600,
    maxDepth: 1400,
    minNormalY: 0.5,
    densityMul: 0.8,
    spacing: 1.4,
    clumpFreq: 0.024,
    clumpAmt: 1.2,
    scaleMin: 0.6,
    scaleMax: 1.6,
    alignToNormal: 0.6,
    sink: 0.1,
    twistAmt: 0.55,
    leanAmt: 0.12,
    lodDist: [34, 74, 136],
    alphaMode: 'none',
  }),
];

export const SPECIES_INDEX: ReadonlyMap<string, number> = new Map(SPECIES.map((s, i) => [s.id, i]));
